name: flutter_template
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  equatable: 2.0.5
  font_awesome_flutter: 10.3.0
  get: 4.6.5
  provider: 6.0.5
  super_editor: 0.2.3+1
  super_editor_markdown: 0.1.4+1
    
  zeronet_ws: 1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true